<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\Reminders\RemindableTrait;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;

class Photo extends Eloquent {

    const UPLOADS_DIR = 'uploads';

    public function getUser()
    {
        return $this->belongsTo('User', 'user');
    }

    public function getLikers()
    {
        return $this->belongsToMany('User', 'likes', 'photo', 'user');
    }

    public function getComments()
    {
        return $this->hasMany('Comment', 'photo');
    }

    public function getPath()
    {
        return self::upload_path($this->filename);
    }

    public function getMimeType()
    {
        $file = new File($this->getPath());
        return $file->getMimeType();
    }

    /**
     * @todo this shouldn't be static; there are probably laravel best practices here
     * @param UploadedFile $file
     * @return string filename that was generated by the save
     */
    public static function persist(File $file)
    {
        $filename = self::filename();
        $file->move(
            self::uploadPath(),
            $filename
        );
        return $filename;
    }

    private static function filename()
    {
        $filename = uniqid();
        return file_exists(self::uploadPath($filename))
            ? self::filename()
            : $filename;
    }

    public static function uploadPath($file = '')
    {
        return storage_path(self::UPLOADS_DIR) . ($file ? ( '/' . $file ) : '');
    }

}
